chore(typescript): prepare TypeScript v6 upgrade
These steps can be performed ahead of the v6 upgrade: tsconfig.json
in this commit is compatible with both v5 and v6.

Switch from baseUrl to paths, because baseUrl is deprecated in v6.

Explicitly set rootDir to avoid this error:

    tsconfig.defs.json:5:5 - error TS5011: The common source directory of 'tsconfig.defs.json'
    is './src'. The 'rootDir' setting must be explicitly set to this or another path to adjust
    your output's file layout.

Migration guide:
https://www.typescriptlang.org/docs/handbook/release-notes/typescript-6-0.html#breaking-changes-and-deprecations-in-typescript-60

Signed-off-by: Simon Ser <contact@emersion.fr>